baseURL = "https://caminale.github.io/my-cv"
languageCode = "en-us"
title = "My CV"
theme = "cv"

[params]
colorDark = "#666"
colorLight = "#fff"
colorPageBackground = "#ddd"
colorPrimary = "#7BA8B1"
colorPrimaryText = "#fff"
colorRightColumnBackground = "#f5f5f5"
colorSecondary = "#aaa"
pages = 1
